### ISSUE TITLE
SimbaDroid at IzzyOnDroid

### ISSUE THREAD

**Issue by IzzySoft** [buttercookie42/SimbaDroid#1]
Just to let you know that SimaDroid was just [published at IzzyOnDroid](https://apt.izzysoft.de/packages/de.buttercookie.simbadroid) and confirmed as [Reproducible Build](https://reproducible-builds.org/) with yesterday's run (see: [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)) – congrats :partying_face:

So you might wish to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme :wink:

Thanks!

**Comment by buttercookie42** [comment]
Hmm, thanks. Funny coincidence, because I was actually just in the process of getting the app into F-Droid – I had just wanted it to reach the featureset of version 0.2/0.3 first to have an at least minimally more friendly UI on how to connect to the SMB server.

Re reproducible builds, I wonder how flaky those will be, because in the process of adding the app to F-Droid [we've stumbled across some strange bit of non-determinism](https://gitlab.com/fdroid/rfp/-/issues/2951).

**Comment by IzzySoft** [comment]
> Funny coincidence

Well, one of my crawlers found your app a few days ago, so I checked and added it :smile: 

> Re reproducible builds

F-Droid uses the tools built by one of our team members, so they see the same issues as we do. Licaon could have a look at the recipe we use (we discovered those "flaky builds" and a solution for them months ago): https://codeberg.org/IzzyOnDroid/rbtlog/src/branch/izzy/log/recipes/de.buttercookie.simbadroid.yml (and yes, the idea with checking the hashes of the affected DEX or PROF files comes from Fay as well – she's the expert on that area).

For some background: there are several issues open with Google for such non-deterministic behavior. Once they are fixed, we… err, probably discover new ones :man_shrugging: We have several such apps in our builders, where the 1..10 loop is used/originates. They usually succeed before reaching 10 (or the build timeout).

**Comment by IzzySoft** [comment]
PS: if you wonder about F-Droid vs. IzzyOnDroid, some hints can be found in [our FAQ](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ).

**Comment by buttercookie42** [comment]
Yeah, I'm roughly aware of the differences, but thanks in any case. Download link added to the readme.

**Comment by IzzySoft** [comment]
Thanks!
